# Generated by Django 5.2.1 on 2025-05-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_tasks', to='todos.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_type',
            field=models.CharField(choices=[('none', '繰り返しなし'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月'), ('custom', 'カスタム')], default='none', max_length=10),
        ),
    ]
