# Generated by Django 5.2.1 on 2025-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_task_due_date_task_parent_task_task_repeat_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
